import type { Metadata } from 'next';
// import { Inter } from 'next/font/google';
// import { SessionProvider } from 'next-auth/react';
import { Provider } from './provider';
import AuthGuard from '@/components/AuthGuard';
import { AntdRegistry } from '@ant-design/nextjs-registry';
import './globals.css';

// const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Next Prisma App',
  description: 'Generated by create next&prisma app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  // const session = await getServerSession();

  return (
    <html lang='en' style={{ height: '100%' }}>
      <body style={{ height: '100%' }}>
        <Provider>
          <AuthGuard>
            <AntdRegistry>{children}</AntdRegistry>
          </AuthGuard>
        </Provider>
      </body>
    </html>
  );
}
